### ISSUE TITLE
Can we use other OS images than those built by AKS team?

### ISSUE THREAD

**Issue by juniwang** [Azure/aks-engine#1066]
**Is this a request for help?**:

Yes.

We are using acs-engine to generate ARM templates and deploy kubernetes clusters. Telling from the generated files, the OS image is built by AKS team:
```
    "ingressosImageOffer": {
      "value": "aks"
    },
    "ingressosImagePublisher": {
      "value": "microsoft-aks"
    },
    "ingressosImageSKU": {
      "value": "aks-ubuntu-1604-201811"
    },
    "ingressosImageVersion": {
      "value": "2018.11.06"
    },
```
And my questions:
- Do we have to use this image offer(or other images built by AKS team)? What should we do if want to use another [image](https://microsoft.sharepoint.com/teams/WAG/EngSys/Implement/OneBranch/Linux%20Secure%20Base%20Image.aspx)(as per requested by audit)? We want to understand the risk/effort if we choose another image.
- What's your base image? Are the security/complience concerns(described in the [secure base image](https://microsoft.sharepoint.com/teams/WAG/EngSys/Implement/OneBranch/Linux%20Secure%20Base%20Image.aspx)) already taken care of?

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

No

**What version of aks-engine?**:

Version: v0.25.3
GitCommit: 0449af5fa
GitTreeState: clean

**Kubernetes version**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
You should be able to use `imageReference` to specify a custom image, see https://github.com/Azure/aks-engine/blob/master/examples/custom-image.json for an example.

The AKS base images are an optimization not a hard requirement. They improve the deployment success rate, and reduce the deployment time. VHD images are based on Ubuntu 16.04-LTS (Ubuntu 18.04-LTS coming soon) and contain pre-installed software needed for AKS Engine cluster deployments that was previously fetched at provisioning time. 

The tradeoffs of not using the provided AKS base image are:
- Longer deployments as the new component version needs to be pulled at provisioning time
- Transient errors due to general download flakes (we do retry every download operation multiple times, but we have seen persistent transient errors happen in the past, before we used a custom base image).

We do not currently use SBI but we are doing some work towards CIS compliance of our VM image. See https://github.com/Azure/aks-engine/projects/7 for tracking.

**Comment by juniwang** [comment]
Thanks a lot, @CecileRobertMichon. It's very helpful. We do see deployment failure from time to time. Your optimizations are important to us since we have many kubernetes and auto-scaler is enabled on all of them.   It's better we keep using the optimized image. Looking forward to seeing your new version with CIS-compliant.
