### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by JonathanAwerty** [Azure/aks-engine#1139]
Hello,

We have a client that has detected a problem when publishing through the master node. It is an environment created in Azure that consists of two slaves and a master node. The problem is that any attempt to access by the master node through port 443 shows "Connection refused". When trying the command "kubectl get pods" it gives a timeout. We opened a case with Microsoft and they told us to open the case here.  They have checked networking (firewall, network security group, ping between VM) and everything is correct. It is an urgent issue because the client needs it already. I attach the logs that they asked me.
[logs.zip](https://github.com/Azure/aks-engine/files/3113041/logs.zip)

**Comment by JonathanAwerty** [comment]
The environment was working previously and nobody modified anything. My customer used scripts to create the resources on Azure.

**Comment by CecileRobertMichon** [comment]
Hi @JonathanAwerty, is this on a cluster created with aks-engine? Can you please share the aks-engine version and the apimodel (with redacted secrets) used to deploy the cluster?

**Comment by JonathanAwerty** [comment]
This cluster was created with acs-engine. I don't really know how to get the versions. 
I tried "kubectl api-versions" but i get dial tcp "Public IP:443: i/o timeout". 
I will ask to the client to share with me the scripts used to deploy this environment but as i said the cluster was working months ago.

**Comment by CecileRobertMichon** [comment]
This would show you the Kubernetes version, not the acs-engine version. You can see the acs-engine version used on the VM tags (see https://github.com/Azure/aks-engine/blob/master/docs/tutorials/deploy.md#checking-vm-tags for instructions), given that the version isn't too old. 

I would recommend upgrading to a newer aks-engine version. That would give you fresh nodes and most likely fix your connection issue. If it doesn't, it will be easier to troubleshoot since it will be using a recent version. See https://github.com/Azure/aks-engine/blob/master/docs/topics/upgrade.md for instructions.

**Comment by JonathanAwerty** [comment]
My customer is working to deploy a new version of Kubernetes using AKS but i need to resolve this with the current configuration while he is putting the new services up. It has to be operational next week.

Any ideas?

**Comment by CecileRobertMichon** [comment]
Have they tried rebooting all the VMs? The connection refused errors could be because the apiserver pod is down and needs to be restarted.

Other than that, it's hard to know what's going on without logs or information about the cluster configuration...

**Comment by JonathanAwerty** [comment]
I just tried to rebooting master node because agents are working and they don't want to risk shutting agents down. As you mentioned all the logs with "api" have the problem.

I'm going to attach again the logs. If you need some specific logs i can give them
 
[logs.zip](https://github.com/Azure/aks-engine/files/3118114/logs.zip)

Thanks,

**Comment by JonathanAwerty** [comment]
I rebooted the two agents and the master node. We did "docker ps" and we saw one apiserver in paused state. We noticed that the api server certificate expired, so we renewed and rebooted the VMs, but the problem still there. 

Here you have what im talking about using "docker ps -a | grep apiserver"

5641ce71d07c        k8s-gcrio.azureedge.net/hyperkube-amd64@sha256:ef3eaeffa4c54a8fae32c7b06b0fa5d2cfe7ae118cf56077c549a3208d066104            "/hyperkube apiser..."   37 seconds ago      Up 36 seconds                                     k8s_kube-apiserver_kube-apiserver-k8s-master-22783496-0_kube-system_b632d43c49941c3bc7e3369256a955d2_8043
a37be7576c05        k8s-gcrio.azureedge.net/hyperkube-amd64@sha256:ef3eaeffa4c54a8fae32c7b06b0fa5d2cfe7ae118cf56077c549a3208d066104            "/hyperkube apiser..."   4 minutes ago       Exited (255) 3 minutes ago                        k8s_kube-apiserver_kube-apiserver-k8s-master-22783496-0_kube-system_b632d43c49941c3bc7e3369256a955d2_8042
ec7a67e94dc7        k8s-gcrio.azureedge.net/pause-amd64:3.1                                                                                    "/pause"                 17 minutes ago      Up 17 minutes                                     k8s_POD_kube-apiserver-k8s-master-22783496-0_kube-system_b632d43c49941c3bc7e3369256a955d2_8

**Comment by CecileRobertMichon** [comment]
How long ago was the cluster deployed?

**Comment by jackfrancis** [comment]
Is it possible apiserver certs expired?

**Comment by DavidArayaSanabria** [comment]
Hi @jackfrancis  and @CecileRobertMichon  this is David from the Azure support, today i worked with them today a found out that the SP expired on 4/20/2019
We renewed the SP for one more year using the same secret and then deallocated and restarted the masters and the worker nodes.

the API logs do not show any service principal issue now:

068       1 cloudprovider.go:59] --external-hostname was not specified. Trying to get it from the cloud provider.\n","stream":"stderr","time":"2019-04-26T16:54:32.461165818Z"}

{"log":"I0426 16:54:32.461469       1 azure.go:175] azure: using client_id+client_secret to retrieve access token\n","stream":"stderr","time":"2019-04-26T16:54:32.46155312Z"}

{"log":"E0426 16:54:32.597674       1 azure_blobDiskController.go:76] azureDisk - getAllStorageAccounts error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/b14c77f4-b41b-455d-8b0b-cf1ad7f07f77/providers/Microsoft.Storage/storageAccounts?api-version=2016-12-01: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '401'\n","stream":"stderr","time":"2019-04-26T16:54:32.597871736Z"}

{"log":"I0426 16:54:32.602148       1 server.go:644] Initializing deserialization cache size based on 0MB limit\n","stream":"stderr","time":"2019-04-26T16:54:32.602237962Z"}

{"log":"I0426 16:54:32.602163       1 server.go:663] Initializing cache sizes based on 0MB limit\n","stream":"stderr","time":"2019-04-26T16:54:32.602251862Z"}

{"log":"I0426 16:54:32.602532       1 azure.go:175] azure: using client_id+client_secret to retrieve access token\n","stream":"stderr","time":"2019-04-26T16:54:32.602732165Z"}

{"log":"E0426 16:54:32.707335       1 azure_blobDiskController.go:76] azureDisk - getAllStorageAccounts error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/b14c77f4-b41b-455d-8b0b-cf1ad7f07f77/providers/Microsoft.Storage/storageAccounts?api-version=2016-12-01: StatusCode=0 -- Original Error: adal: Refresh request failed. Status Code = '401'\n","stream":"stderr","time":"2019-04-26T16:54:32.707616592Z"}

{"log":"I0426 16:54:32.995915       1 reader.go:56] Loaded 8 audit policy rules from file /etc/kubernetes/manifests/audit-policy.yaml\n","stream":"stderr","time":"2019-04-26T16:54:32.996100917Z"}

{"log":"I0426 16:54:32.997780       1 storage_factory.go:290] storing { serviceaccounts} in v1, reading as __internal from storagebackend.Config{Type:\"etcd3\", Prefix:\"/registry\", ServerList:[]string{\"https://127.0.0.1:2379\"}, KeyFile:\"/etc/kubernetes/certs/etcdclient.key\", CertFile:\"/etc/kubernetes/certs/etcdclient.crt\", CAFile:\"/etc/kubernetes/certs/ca.crt\", Quorum:true, Paging:false, DeserializationCacheSize:1000, Codec:runtime.Codec(nil), Copier:(*runtime.Scheme)(0xc4202fc0c0), Transformer:value.Transformer(nil), CompactionInterval:300000000000}\n","stream":"stderr","time":"2019-04-26T16:54:32.997897128Z"}

{"log":"I0426 16:54:32.997836       1 storage_factory.go:290] storing { secrets} in v1, reading as __internal from storagebackend.Config{Type:\"etcd3\", Prefix:\"/registry\", ServerList:[]string{\"https://127.0.0.1:2379\"}, KeyFile:\"/etc/kubernetes/certs/etcdclient.key\", CertFile:\"/etc/kubernetes/certs/etcdclient.crt\", CAFile:\"/etc/kubernetes/certs/ca.crt\", Quorum:true, Paging:false, DeserializationCacheSize:1000, Codec:runtime.Codec(nil), Copier:(*runtime.Scheme)(0xc4202fc0c0), Transformer:value.Transformer(nil), CompactionInterval:300000000000}\n","stream":"stderr","time":"2019-04-26T16:54:32.997909928Z"}

{"log":"I0426 16:54:32.998737       1 logs.go:41] warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated\n","stream":"stderr","time":"2019-04-26T16:54:32.999122235Z"}

{"log":"I0426 16:54:32.999680       1 logs.go:41] warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated\n","stream":"stderr","time":"2019-04-26T16:54:32.99999544Z"}

{"log":"I0426 16:54:32.999733       1 compact.go:54] compactor already exists for endpoints [https://127.0.0.1:2379]\n","stream":"stderr","time":"2019-04-26T16:54:33.00000704Z"}

{"log":"I0426 16:54:33.001431       1 services.go:51] Setting service IP to \"10.0.0.1\" (read-write).\n","stream":"stderr","time":"2019-04-26T16:54:33.001549249Z"}

However, the problem persists since docker ps -a | grep apiserver shows the api paused

5641ce71d07c k8s-gcrio.azureedge.net/hyperkube-amd64@sha256:ef3eaeffa4c54a8fae32c7b06b0fa5d2cfe7ae118cf56077c549a3208d066104 "/hyperkube apiser..." 37 seconds ago Up 36 seconds k8s_kube-apiserver_kube-apiserver-k8s-master-22783496-0_kube-system_b632d43c49941c3bc7e3369256a955d2_8043
a37be7576c05 k8s-gcrio.azureedge.net/hyperkube-amd64@sha256:ef3eaeffa4c54a8fae32c7b06b0fa5d2cfe7ae118cf56077c549a3208d066104 "/hyperkube apiser..." 4 minutes ago Exited (255) 3 minutes ago k8s_kube-apiserver_kube-apiserver-k8s-master-22783496-0_kube-system_b632d43c49941c3bc7e3369256a955d2_8042
ec7a67e94dc7 k8s-gcrio.azureedge.net/pause-amd64:3.1 "/pause" 17 minutes ago Up 17 minutes k8s_POD_kube-apiserver-k8s-master-22783496-0_kube-system_b632d43c49941c3bc7e3369256a955d2_8


--Suggested to deallocate all the machine, then start the master alone, wait until it is completely up and the proceed to start back the worker nodes.

**Comment by JonathanAwerty** [comment]
I deallocated all the machines and then started the master alone. I tried to do the commands without agents and i get the same message "connection refused". I started the two agents but the problem still happening.

**Comment by jackfrancis** [comment]
If we're talking about a cluster that we're attempting to recover by deleting all active workloads, reboot all nodes, in order to apply changes to the service principal... why not create a new cluster? As there are many possible entropy vectors in a cluster that is at least one year old, and we're already in a non-operational state, a new cluster would be recommended going forward.

**Comment by JonathanAwerty** [comment]
Good afternoon,

We decided to delete de ACS environment and create a new one with AKS wich is working without issues.

Thanks to everybody for the support.

**Comment by jackfrancis** [comment]
Thank you for checking back @JonathanAwerty!
