### ISSUE TITLE
Kata URL has changed and needs to be updated in the code

### ISSUE THREAD

**Issue by sidray7965** [Azure/aks-engine#1387]
**Is this a request for help?**:

Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of aks-engine?**:
0.34.3
---

**Kubernetes version**:
1.14

**What happened**:
Not able to use kata-container runtime using aks-engine.

**What you expected to happen**:
kata-container runtime should have been provisioned.

**How to reproduce it** (as minimally and precisely as possible):
Just create a cluster using aks-engine and in the ARM template:
        "containerRuntime": "kata-containers",

**Anything else we need to know**:

**Comment by sidray7965** [comment]
@CecileRobertMichon: Can you please take a look at this.

**Comment by CecileRobertMichon** [comment]
Thanks for reporting @sidray7965. It looks like the URL in https://github.com/Azure/aks-engine/blob/master/parts/k8s/cloud-init/artifacts/cse_install.sh#L133 needs to be modified slightly to match https://github.com/kata-containers/documentation/blob/master/install/ubuntu-installation-guide.md.

I'm going to go ahead and label this good-first-issue since this should be an easy one to fix. Feel free to open a PR if you'd like to see this fixed sooner rather than later.

**Comment by sidray7965** [comment]
Thanks @CecileRobertMichon 

cc: @nikitozz

**Comment by sidray7965** [comment]
Thank you everyone!

**Comment by sidray7965** [comment]
@CecileRobertMichon When can we get another release.

**Comment by CecileRobertMichon** [comment]
We will release a patch as soon as https://github.com/Azure/aks-engine/pull/1403 is merged, I'll make sure to include the Kata fix as well. ETA is end of day (PST).

**Comment by sidray7965** [comment]
Thanks for the update Cecile. I will look forward to the release.

**Comment by CecileRobertMichon** [comment]
Done: https://github.com/Azure/aks-engine/releases/tag/v0.36.3
