### ISSUE TITLE
Standard_D2_v3 does not support AgentPoolProfile.acceleratedNetworking

### ISSUE THREAD

**Issue by idanlevin** [Azure/aks-engine#1531]
**Describe the bug**
I tried to create a new cluster with accelerated networking enabled and got the error:
`Standard_D2_v3 does not support AgentPoolProfile.acceleratedNetworking`

**Steps To Reproduce**
```json
{
	"apiVersion": "vlabs",
	"properties": {
		"orchestratorProfile": {
			"orchestratorType": "Kubernetes",
			"orchestratorRelease": "1.15",
			"kubernetesConfig": {
				"useManagedIdentity": true,
				"addons": [{
						"name": "cluster-autoscaler",
						"enabled": true,
						"config": {
							"minNodes": "1",
							"maxNodes": "5"
						}
					}
				]
			}
		},
		"masterProfile": {
			"count": 1,
			"dnsPrefix": "",
			"vmSize": "Standard_D2_v3"
		},
		"agentPoolProfiles": [{
				"name": "agents",
				"count": 1,
				"vmSize": "Standard_D2_v3",
				"availabilityProfile": "VirtualMachineScaleSets",
				"storageProfile": "ManagedDisks",
				"acceleratedNetworkingEnabled": true
			}
		],
		"linuxProfile": {
			"adminUsername": "idan",
			"ssh": {
				"publicKeys": [{
						"keyData": ""
					}
				]
			}
		}
	}
}
```
**Expected behavior**
The cluster should have been created

**AKS Engine version**
0.37.3
**Kubernetes version**
1.15
**Additional context**
Based on the example here: https://github.com/Azure/aks-engine/blob/patch-release-v0.37.3/examples/kubernetes-config/kubernetes-accelerated-network.json it should work

**Comment by CecileRobertMichon** [comment]
Good catch @idanlevin. `Standard_D2_v3` in fact does _not_ support acdelerated networking, as per https://docs.microsoft.com/en-us/azure/virtual-network/create-vm-accelerated-networking-cli#supported-vm-instances, as it only has 2 vCPUs: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-general#dv3-series-1 

https://github.com/Azure/aks-engine/commit/813c78e87552bf3984515f361a1299723a1c7b8c changed the VM size in https://github.com/Azure/aks-engine/blob/patch-release-v0.37.3/examples/kubernetes-config/kubernetes-accelerated-network.json as it was doing a search and replace of all v2 series.

We should replace the VM size in the example by `Standard_D4_v3`, which does support accelerated networking.

I'll label this a good first issue since it's a one line change.
