### ISSUE TITLE
Support aks-engine add and remove agent pools

### ISSUE THREAD

**Issue by mo-saeed** [Azure/aks-engine#1611]
**Describe the request**
I think that would be really great after the standard loadbalancer is really stable to support aks-engnie add/remove agent-pool commands.

Also aks-engine upgrade single agent pool. that would be great for testing new version of k8s first before applying it on all agent pools.

This already supported with the hosted aks.

**Explain why AKS Engine needs it**
Manage the agent pools with aks-engine commands.

**Describe alternatives you've considered**
Apply this manually with arm templates, but this will not work with the single agent-pool upgrade from example.

**Additional context**

**Comment by mo-saeed** [comment]
Is there any plans to implement this ?, this is already in aks. wondering why not in aks-engine.

**Comment by jackfrancis** [comment]
Hi @mo-saeed at present any additional cluster lifecycle foo in aks-engine is being gathered as requirements for a re-implementation of this entire area within aks-engine. Stay tuned!

**Comment by mo-saeed** [comment]
Thanks @jackfrancis !

**Comment by pierluigilenoci** [comment]
@jackfrancis Any news on this topic?

**Comment by CecileRobertMichon** [comment]
https://github.com/Azure/aks-engine/pull/2209

**Comment by pierluigilenoci** [comment]
@CecileRobertMichon now #2209 is closed. So what? :(

**Comment by CecileRobertMichon** [comment]
@pierluigilenoci #2209 was closed because it was stale, ie. we didn't close it because we don't want the change, the bot closed it because there wasn't any activity in the PR recently. I believe the author didn't have time to see it to completion but the ask is still there and the initial work he did is a very good start for anyone to pick it up and start from there. I'm going to mark this one as help wanted.

/help

Also see https://github.com/Azure/aks-engine/pull/2209#issuecomment-571288857 for a manual workaround in the meantime. That PR is just adding the  CLI command to do the same thing with a nicer UX.

**Comment by CecileRobertMichon** [comment]
@pierluigilenoci take a look at #2557 :) 

/assign @DavidLangworthy
