### ISSUE TITLE
revert distro const name change

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#1652]
to accommodate older api models, let's re-add back the const values for distro values

**Comment by CecileRobertMichon** [comment]
to clarify, the const was kept as `AKS1604Deprecated` https://github.com/Azure/aks-engine/blob/master/pkg/api/const.go#L32

The issue is that it doesn't map to an image reference in the cloud -> image maps (pkg/api/azenvtypes.go), so any apimodel using that distro will have an empty image reference value in its template.
