### ISSUE TITLE
Add support for dedicated hosts

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#1711]
Dedicated Hosts is currently in public preview:

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/dedicated-hosts

Let's add support for this VM type (it will be a 3rd type, after VMAS and VMSS). See here for a reference example:

https://github.com/Azure/azure-quickstart-templates/blob/master/201-vm-dedicated-hosts/azuredeploy.json

**Comment by prbajrac** [comment]
@jackfrancis Do you have any information on ETA for this feature or is this still in conception ?

**Comment by devigned** [comment]
@prbajrac I'm going to start diving into this work today. Being pretty new to aks-engine, I'm not sure what the ETA is right now. I'll have a better idea in a couple days. 

Why do you ask?

**Comment by prbajrac** [comment]
@devigned Customer had inquired on this issue and saw freshly opened issue here. Let me know over here when you have a better idea.

**Comment by devigned** [comment]
Will do!

**Comment by devigned** [comment]
@jackfrancis I think the dedicated hosts feature is a little different than `availabilityProfile`. That is to say, that dedicated hosts should, at some point, run both availability sets and vmss (I think based on documentation). So really, this is more like introducing a new dimension, perhaps `hostingProfile=[Dedicated|Shared]`, rather than another option to `availabilityProfile`.

Reading [this documentation](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/dedicated-hosts#host-life-cycle) is what prompted this theory.

What do you think?

**Comment by edernucci** [comment]
Hi people, any updates on this issue?

**Comment by kshke** [comment]
Hi Team

Do we support dedicated hosts now？

**Comment by jackfrancis** [comment]
Hi @kshke, no, it's not implemented yet.
