### ISSUE TITLE
Invalid JSON in azure.json on Windows Nodes

### ISSUE THREAD

**Issue by vyta** [Azure/aks-engine#1779]
**Describe the bug**
Invalid JSON in azure.json on Windows nodes due to trailing comma: ```"userAssignedIdentityID": ,``` 
**Steps To Reproduce**

**Expected behavior**
Valid JSON in azure.json

**AKS Engine version**
 v0.38.5-aks

**Kubernetes version**
1.14.4

**Additional context**
Discovered while attempting to implement [hexadite's kayvault-agent](https://github.com/Hexadite/acs-keyvault-agent) on Windows

**Comment by CecileRobertMichon** [comment]
@marosset any ideas?

**Comment by marosset** [comment]
I can take a look.

**Comment by marosset** [comment]
It looks like the powershell here needs to be updated to wrap the value in quotes to produce correct json if the value is empty "userAssignedIdentityID": "", instead of "userAssignedIdentityID": ,
https://github.com/Azure/aks-engine/blob/0192361d3310daa9e4a8b77b5aca83bec8935abb/parts/k8s/windowskubeletfunc.ps1#L70

@vyta can you provide repro steps or would you be able to validate a fix?
