### ISSUE TITLE
Should always change the node name to lower case before draining it

### ISSUE THREAD

**Issue by chengliangli0918** [Azure/aks-engine#1982]
**Describe the bug**
For VMSS cluster, the virtual machine in Azure (instance name), and the machine name in OS and node name in Kubernetes is different, for example, for VMSS instance with instance id 11
The Instance name in Azure: aks-nodepool1-12345678-vmss_11
The machine name in OS:      aks-nodepool1-12345678-vmss00000B
The node name in Kubernetes: aks-nodepool1-12345678-vmss00000b

The upgrader gets the virtual machines to be upgraded using machine name in OS. So we should change the name to lower case before draining it. Otherwise the draining will fail with 'node not found' error.

https://github.com/Azure/aks-engine/blob/master/pkg/operations/kubernetesupgrade/upgrader.go#L692

**Steps To Reproduce**

**Expected behavior**

**AKS Engine version**

**Kubernetes version**

**Additional context**

**Comment by CecileRobertMichon** [comment]
this was already fixed in https://github.com/Azure/aks-engine/pull/951, I think the code agt https://github.com/Azure/aks-engine/blob/master/pkg/operations/kubernetesupgrade/upgrader.go#L692 was added after that and didn't handle uppercase names. Maybe we should look into a more general fix so that it doesn't have to be handled everytime we reuse VMSS node names in the upgrade code...
