### ISSUE TITLE
Enable Dynamic Kubelet Configuration

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#2154]
Enable in-place kubelet runtime configuration changes by implementing the "Dynamic Kubelet Configuration" spec defined here:

https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/

**Comment by CecileRobertMichon** [comment]
for reference, this is how kubeadm does it: https://sourcegraph.com/github.com/kubernetes/kubernetes@cb19b56831d54d1d31249949318ef0b07bf00df9/-/tree/cmd/kubeadm/app/phases/kubelet

**Comment by CecileRobertMichon** [comment]
Did some investigation on this, it's not a straight forward change. The way our current kubelet config UX works with a map[string]string makes it really hard to change to looking for specific config values without breaking back compat. Also, both config via config file and dynamic config are beta but I don't see an easy way to enable this behind a feature flag, which isn't ideal. There's also the question of how to do this for Windows since Windows currently passes the flags to CSE right now. I think this is at least a few weeks of work and something that we should probably agree on a design and backcompat/upgrade strategy for.

**Comment by jackfrancis** [comment]
No plans to do this work.
