### ISSUE TITLE
Do not reset custom mobyVersion on cluster upgrade

### ISSUE THREAD

**Issue by serbrech** [Azure/aks-engine#2489]
**Describe the request**
We can currently override the mobyVersion installed and configured on the nodes.
However this gets reset to the AKS-Engine defined default version on subsequent upgrades

**Explain why AKS Engine needs it**
I think it's fair that if you define a custom version, aks-engine does not override it.
changing the engine version should be a user-driven decision. silently resetting an upgrade is exposing the user to unexpected, hard to track behaviors.

**Describe the solution you'd like**
remove the isUpdate from this if check : https://github.com/Azure/aks-engine/blob/e0b7f9ad0aee4db4d044bf7a90176d23e8cd5ea2/pkg/api/defaults.go#L158

**Describe alternatives you've considered**
- overriding the template after generation
- no applying aks-engine defaults when generating the templates

**Additional context**
AKS would benefit from this in emergency situations... :)

/cc @wenwu449

**Comment by CecileRobertMichon** [comment]
I believe this is by design... And that property is only meant for dev purposes as documented in https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md#kubernetesconfig

The reasoning behind this is that without `isUpdate` there, the Moby version will not get updated to the latest default version during cluster upgrades which means that the cluster will always keep the same Moby version that it was created with. This is an issue, especially when if there is a Moby CVE.

**Comment by serbrech** [comment]
yes, that would be the expected behavior.
if same as if I set the k8s version, I don't expect aks-engine to upgrade me even if there is a CVE.
if you want to reset to the default version, you can remove the custom version and let aks-engine do its internal magic.

**Comment by serbrech** [comment]
I think it's unexpected that doing a create, then not doing any changes, and doing an upgrade is actually downgrading a key cluster component
