### ISSUE TITLE
Determine what customDimensions we want for CSE telemetry

### ISSUE THREAD

**Issue by marosset** [Azure/aks-engine#2543]
We should settle on what data we want reported as customDimensions for telemetry collected by app insights during CSE execution.

Here is a what I was thinking we start with:
- correlationd_id - (unique guid generated during each CSE run)
- k8s_version
- os_type - (linux, windows)
- os_version
- network_plugin - (kubelet, azurecni, etc)
- network_plugin_version
- network_mode (L2Bridge, overlay, etc)
- cri - (docker, containerd, etc)
- cri_version
- lb_sku 
- location - (azure region)
- vm_sku
- vhd_id - (a unique identifier for aks-engine specific VHDs  or empty)

**Comment by marosset** [comment]
I was thinking if there was a way to generate a new guid each time ARM deployments were generated we could pass that in to the CSEs to to be able to correlate different CSE executions that were part of the same deployment.

**Comment by PatrickLang** [comment]
Here's a few ideas:

Should:

- AcceleratedNetworking - true/false
- DeploymentType - VMSS / AvailabilitySet
- quantity/sku of managed disks attached
- Encryption Mode - default, BYOK, ? . Azure encrypts all disks by default but people can opt into other modes with more specific controls around key usage & ownership.

Maybe

- Storage SKU for OS drive
- Storage size for OS drive (because IOPs are scaled within a SKU based on size)

**Comment by PatrickLang** [comment]
Do we have any way to track the age of the template? VM instances may be short lived since they're scaled. It would be good to know if someone is reusing the same VMSS (and therefore the same node pool) for some length of time. That could help provide details on how long to test/support given aks-engine versions. If they're not changing the settings the same VMSS template could be used for months at a time.
