### ISSUE TITLE
Support for Automatic OS image upgrades for windows nodes

### ISSUE THREAD

**Issue by yixwang** [Azure/aks-engine#2577]
**Describe the request**
We are looking for solutions for keep windows nodes in the VMSS update to date with security patches. 

Our current approach is to have "enableAutomaticUpdates" set to true. Then the security patch will be automatically installed when become available. Then at some point these nodes are manually restarted to apply the changes. We are looking for ways to improve this as this requires manual intervention. 

One approach we looked into is Automatic OS image upgrades supported by VMSS. According to the doc: https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-automatic-upgrade, this approach swaps the OS disk basically and can do so in a rolling manner. It also says "Only certain OS platform images are currently supported. Custom images aren't currently supported.". Since we are using the default windows image published by microsoft-aks, it doesn't seem to support Automatic OS image upgrade. 

I assume the aks-engine team has thought about this one. Would like to understand if there's any plan to integrate "Automatic OS image upgrades" into aks-engine. 

**Explain why AKS Engine needs it**
To keep the cluster secure and apply security patches for windows nodes automatically. 

**Describe the solution you'd like**
make if configurable in the apimodel.json with some settings like 
```
"enableAutomaticOsImageUpgrade": true
```

**Describe alternatives you've considered**
kured for windows but it's currently not avaiable

**Additional context**

**Comment by marosset** [comment]
It looks like this is configurable today by setting windowsProfile.enableAutomaticUpdates and defaults to false.

https://github.com/Azure/aks-engine/blob/623e9ae0b7bc4ca5d198993e74027eac6644c13f/pkg/api/vlabs/types.go#L173

In 2019 we ran into a number of issues where monthly security patches were released with regressions for windows containers and/or windows Kubernetes support.
Because of this our current approach and recommendation is to keep OS patching as a manual operation to be performed with adequate testing.
I think this flag was removed from the docs for the same reason.
