### ISSUE TITLE
Cached files on Windows vhd are being downloaded

### ISSUE THREAD

**Issue by MikkelHegn** [Azure/aks-engine#3139]
**Describe the bug**
The `hns.psm1` file is being used twice in the Windows provisioning script:
1. https://github.com/Azure/aks-engine/blob/5ee1274e2cf83ee3979e57890058ca5d011b153f/parts/k8s/kuberneteswindowssetup.ps1#L340
1. https://github.com/Azure/aks-engine/blob/5ee1274e2cf83ee3979e57890058ca5d011b153f/parts/k8s/kuberneteswindowssetup.ps1#L385

When running the second function, the file is not found in the cache location, hence being downloaded from GitHub.

**Steps To Reproduce**
Deploy a Windows node.

**Expected behavior**
The cached file is used.

**AKS Engine version**
0.47.0 (Current aks version)

**Kubernetes version**
1.16.x

**Additional context**
Windows vhd 17763.1075.200227

**Comment by MikkelHegn** [comment]
@marosset / @ksubrmnn - this is impacted locked down environments and blocking node provisioning.

I suggest we also don't block node provisioning if downloading debug script fails (Get-LogCollectionScripts).

**Comment by marosset** [comment]
This issue was addressed in aks-engine v0.48.0 and a jenkins job was added to validate no-outbound functionality for each aks-engine release.
Both the fix and the test updates were part of #2883 

The same test job should be enabled in the branch AKS uses to vendor in aks-engine if this is a continued problem.

**Comment by MikkelHegn** [comment]
Thanks @marosset - can you or @AbelHu help setting up that validation?
