### ISSUE TITLE
Expose AzureCNIVersion in apimodel

### ISSUE THREAD

**Issue by davidmatson** [Azure/aks-engine#320]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
---

AzureCNIVersion isn't included in the KubernetesConfig doc list. Based on a quick search through the source, I believe setting this property is the right way to get a different version of this plugin installed.

**Comment by davidmatson** [comment]
Actually, AzureCNIVersion doesn't seem to work. What's the right way to choose a custom version?

**Comment by zhiweiv** [comment]
https://github.com/Azure/azure-container-networking/issues/287 works for me.

**Comment by CecileRobertMichon** [comment]
Hi @davidmatson, the AzureCNIVersion is not currently user configurable in the apimodel.

**Comment by davidmatson** [comment]
Thanks. I'll try azureCNIURLWindows instead. If we could expose AzureCNIVersion (without the required "v" prefix for consistency), that would be great too.

**Comment by davidmatson** [comment]
Yes, I was able to use the full URL for now. Thanks.

**Comment by jackfrancis** [comment]
Removing the "help wanted" label because I think we want to use this particular request as an excuse to generalize "user-configurable k8s pre-reqs". Rather than simply bolt on Azure CNI version as a user-configurable feature in an existing flat structure (e.g., `KubernetesConfig`) we'd benefit in the long term by having this type of configuration be structured and implemented in a way that was distinct, and could accommodate independent maintenance (i.e., not have to deliver a change to the Azure CNI version with an entire cluster upgrade operation).

**Comment by marosset** [comment]
Bumping this issue.
@rjaini ran into an issue where AzureCNI version was changed but packages for the new version were not present in the Windows VHD which broke in a disconnected scenario.

**Comment by jackfrancis** [comment]
No plans to change this configuration. As it stands now, this is the exception to most api model properties, in that it is read-only.
