### ISSUE TITLE
cloud controller manager broken for Windows

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#3453]
Seems to be easily reproducible:

1) Enable cloud controller manager in your api model, e.g.:

```
...
      "orchestratorProfile": {
          "orchestratorType": "Kubernetes",
          "kubernetesConfig": {
              "useCloudControllerManager": true
          }
      }
...
```

Include a Windows node pool. Nodes are provisioned, but never seem to join the cluster.

**Comment by jackfrancis** [comment]
Relevant test config showing this failure:

https://github.com/Azure/aks-engine/blob/master/test/e2e/test_cluster_configs/cloud_controller_manager.json

**Comment by marosset** [comment]
@chewong do you know if CCM + Windows was ever testing in aks-engine?

**Comment by chewong** [comment]
Yea the test was included in https://github.com/Azure/aks-engine/pull/3044

**Comment by chewong** [comment]
https://github.com/Azure/aks-engine/blob/master/parts/k8s/windowscsiproxyfunc.ps1#L14-L15 isn't able to extract csi-proxy binary from https://kubernetesartifacts.azureedge.net/csi-proxy/v0.1.0/binaries/csi-proxy.tar.gz since the file structure has changed. I will trigger a Jenkins run to validate the change once it's fixed.

**Comment by jackfrancis** [comment]
Thanks for hunting down, @chewong!

**Comment by chewong** [comment]
The CSI proxy download link has been fixed, verified by https://upstream.jenkins.azure-containers.io/blue/organizations/jenkins/k8s-create-cluster-matrix/detail/k8s-create-cluster-matrix/229/pipeline.
