### ISSUE TITLE
Add Restart=always to cron systemd service to ensure cron always restarts

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#3503]
Currently an 18.04 cron service looks like this:

```
$ sudo cat /lib/systemd/system/cron.service 
[Unit]
Description=Regular background program processing daemon
Documentation=man:cron(8)

[Service]
EnvironmentFile=-/etc/default/cron
ExecStart=/usr/sbin/cron -f $EXTRA_OPTS
IgnoreSIGPIPE=false
KillMode=process

[Install]
WantedBy=multi-user.target
```

Which means if cron crashes, it won't be started back up again unless it's manually started, or the node is rebooted.

**Comment by jackfrancis** [comment]
For bonus points see what Flatcar does

**Comment by Michael-Sinz** [comment]
For our skyman platform, we will be injecting this bit of logic into the nodes.  (Note that this is the cut-n-paste of the section of code and thus it is known to work)

```
# If we find that there is a cron.service and it does not have the
# auto-restart setting, we will fix that here.  It is a function
# such that it can run async of the rest of the work and have "locals."
function fix_cron_auto_restart()
{
    local CRON_SERVICE=/lib/systemd/system/cron.service
    # We only do the restart policy update work if there is not one
    if [[ -f ${CRON_SERVICE} ]]; then
        if ! grep -q 'Restart=' ${CRON_SERVICE}; then
            # Add a restart policy since there was none
            sed -i 's/\[Service\]/[Service]\nRestart=always/' ${CRON_SERVICE}
            systemctl daemon-reload
        fi
    fi
}
fix_cron_auto_restart
```

**Comment by Michael-Sinz** [comment]
We have found that cron is rather solid but it has failed on a few nodes - and usually very early on.

Note that it was a bug that 16.04 and 18.04 do not set the restart policy for cron.  In 20.04, the restart policy was added.  If someone does not want run, they can just stop it via systemctl.

Cron is critical for many system operations and having it exit and never restart can cause numerous problems.  Somehow, at scale, with thousands of new VMs provisioned each day, we see one of these every once in a while (weekly or so, since we started looking - we had not been looking for cron failures as they are unexpected and it was even more unexpected that cron would not automatically restart...)
