### ISSUE TITLE
Add e2e test for ipv6 windows dual stack support

### ISSUE THREAD

**Issue by jsturtevant** [Azure/aks-engine#3568]
**Describe the request**
Add e2e test and documentation for [ipv6 windows dual stack support](https://github.com/Azure/aks-engine/pull/3415).  Windows Dual stack support is now available in the [1.19-beta release](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#feature) and [2004](https://github.com/Azure/aks-engine/pull/3516) support has been enabled in aks-engine.

**Explain why AKS Engine needs it**
prevent regressions 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jsturtevant** [comment]
@tamilmani1989 are you able to help with this?

**Comment by tamilmani1989** [comment]
@jsturtevant i think @aramase planning e2e tests for kubenet dualstack. Once he did that, i will extend it for azure cni

**Comment by jsturtevant** [comment]
Thanks for the update.  I thought it had landed in 2004 but now understand it is coming in the next SAC release. Putting this issue on hold until that is released.

**Comment by daschott** [comment]
@jsturtevant IPv6 support is being backported to 2004... Tentative ETA is in October.

**Comment by bridgetkromhout** [comment]
@aramase I think we intend for all such tests to be accomplished with CAPZ, not AKS Engine- can you address this? Thanks.

**Comment by aramase** [comment]
This issue was specifically for adding tests in aks-engine for IPv6 cluster creation to prevent any regression. For CAPZ, IPv6 cluster creation is already part of the PR gate.

**Comment by bridgetkromhout** [comment]
Thanks, @aramase! To summarize our discussion:
* Single stack IPv6 is already supported in CAPZ and is tested as part of the PR gate. 
* [Dual-stack support needs to be added to CAPZ](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1266)
* [Switching testing from AKS Engine to CAPZ](https://github.com/kubernetes-sigs/cloud-provider-azure/issues/1138)

Because we are not adding this testing in AKS Engine, and the specific needs listed above are tracked elsewhere, I will now resolve this issue.
