### ISSUE TITLE
Azure stack deployment template update

### ISSUE THREAD

**Issue by panchul** [Azure/aks-engine#3858]
**Describe the request**
I am requesting to add apiServer information to the sample deployment .json for istio-sytem, `examples/azure-stack/kubernetes-azurestack.json` . I propose to  the following would go to "properties">"orchestratorProfile">"kubernetesConfig":

```
"apiServerConfig": {
        "--service-account-api-audiences": "api,istio-ca",
        "--service-account-issuer": "kubernetes.default.svc",
        "--service-account-signing-key-file": "/etc/kubernetes/certs/apiserver.key"
}```
Or at least have a place-holder for "apiServerConfig" for people to be able to update their service-account locations.

**Explain why AKS Engine needs it**

Without this update `istio-system` has problems(pods do not come up). Every time people get this sample template, they have to lookup the solution, which is often not easy for non-infrastructure people. 

**Describe the solution you'd like**

It is a nuance described in https://github.com/Azure/aks-engine/blob/master/examples/service-mesh/README.md ,
Adding "apiServerConfig" resolved it for the clusters I have been creating, I presume others would benefit from it too.

**Describe alternatives you've considered**

I had to use older versions of Istio, which is not an ideal option if Istio is a part of another package.

**Additional context**

**Comment by jadarsie** [comment]
Hello @panchul, my understanding is that each example shows how to achieve a particular goal and then it is up to the user to come up with a cluster definition that puts everything together. I would rather keep it separate so it is clear that the extra "istio" parameters are not required in order to deploy a cluster on Azure Stack.

We can make the "istio" example easier to find by adding a [FAQ](https://github.com/Azure/aks-engine/blob/master/docs/topics/azure-stack.md#frequently-asked-questions) to the Azure Stack topic page. Would that be useful at all?

**Comment by panchul** [comment]
@jadarsie , yes, thanks. I agree istio is not a mandatory part of the deployment. And as long as the users could look up the solution to this situation, it should be good.

**Comment by jadarsie** [comment]
@panchul see #3988 for related work
