### ISSUE TITLE
All Service Account tokens are invalid after aks-engine upgrade

### ISSUE THREAD

**Issue by antoineco** [Azure/aks-engine#391]
**Is this a request for help?**: no

---

**Is this an ISSUE or FEATURE REQUEST?**: issue

---

**What version of aks-engine?**: v0.28.1

---

**Kubernetes version**: from v1.8.14 to v1.9.10

**What happened**: after using `aks-engine upgrade --deployment-dir ./output/mycluster --upgrade-version 1.9.10` to roll-out a new Kubernetes version, all ServiceAccount tokens are invalidated and one has to delete them manually in order to force their recreation.

Before running that command, we regenerate the `output/` directory using `aks-engine generate apimodel.json --ca-certificate-path ca.crt --ca-private-key-path ca.key --output-directory ./output`. I can confirm the Certificate Authority didn't change during the update, and clients that use x509 authentication (etcd and k8s components typically) are not affected.

**What you expected to happen**: all tokens remain valid since the CA is still the same.

**How to reproduce it**: save the following file and use it as a base to execute the commands above.

<details>
  <summary>apimodel.json</summary>

```json
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "kubernetesConfig": {
        "enableRbac": false,
        "clusterSubnet": "10.244.0.0/16",
        "networkPolicy": "none"
      },
      "orchestratorVersion": "1.8.14"
    },
    "masterProfile": {
      "count": 1,
      "storageProfile": "ManagedDisks",
      "vmSize": "Standard_F2s",
      "firstConsecutiveStaticIP": "172.16.0.200",
      "dnsPrefix": "mycluster",
      "vnetSubnetId": "<redacted>"
    },
    "agentPoolProfiles": [
      {
        "count": 1,
        "name": "pool1",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile": "ManagedDisks",
        "vmSize": "Standard_A2m_v2",
        "osType": "Linux",
        "vnetSubnetId": "<redacted>"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "<redacted>"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "<redacted>",
      "secret": "<redacted>"
    }
}
```
</details>

.

**Anything else we need to know**:

**Comment by antoineco** [comment]
> Did you re-generate the deployment files before running upgrade?

Yes, that's what I did. The reason for that is that we only store PKI assets and the original API model definition. My expectation was that those 3 files would allow us to regenerate the deployment + parameter files.

In practice the update completes successfully using that flow, except for the SA tokens that are not valid anymore.

I'm trying to pinpoint what could have gone wrong in the process. SA tokens are signed by the CA, so what could invalidate them during the rolling update?

**Comment by CecileRobertMichon** [comment]
did you regenerate the templates from the same version of aks-engine that you originally deployed with? In practice you are correct that only the apimodel should be needed but in practice upgrade currently relies on the parameters file as outlined in the documentation:

`You will need access to the original _output/ directory files that were generated during cluster deployment in order to run upgrade. aks-engine will use the --deployment-dir argument provided in the upgrade command to introspect the apimodel.json file and Azure Resource Manager (ARM) parameters in order to determine the cluster's current Kubernetes version, as well as all other cluster configuration data as defined by aks-engine during the last time that aks-engine was used to deploy, scale, or upgrade the cluster.`

We have an [issue](https://github.com/Azure/aks-engine/issues/361) open for changing this but at the moment regenerating the templates for upgrade is not a supported scenario.

**Comment by antoineco** [comment]
Unfortunately not, we moved from an older acs-engine to aks-engine and regenerated the output using the later. Bummer.

Anyway, thanks for the confirmation @CecileRobertMichon :raised_hands:
