### ISSUE TITLE
Private cluster loadbalancer creating public IP and SNAT for outbound connections

### ISSUE THREAD

**Issue by NaveenkumarIyappan** [Azure/aks-engine#4106]
**Describe the bug**
When `loadBalancerSku:standard` creates a SNAT with outbound internet rule even while creating private cluster `privateCluster:true`

**Steps To Reproduce**

```
{
	"apiVersion": "vlabs",
	"location": "westus2",
	"properties": {
		"orchestratorProfile": {
			"orchestratorType": "Kubernetes",
			"orchestratorRelease": "1.18",
			"kubernetesConfig": {
				"networkPlugin": "flannel",
				"loadBalancerSku": "Standard",
				"excludeMasterFromStandardLB": true,
				"privateCluster": {
					"enabled": true
				},
				"apiServerConfig": {
					"--kubelet-preferred-address-types": "InternalIP"
				},
				"addons": [{
						"name": "kubernetes-dashboard",
						"enabled": true
					}, {
						"name": "cluster-autoscaler",
						"enabled": true,
						"pools": [{
								"name": "agentpool",
								"config": {
									"min-nodes": "6",
									"max-nodes": "24"
								}
							}
						],
						"config": {
							"scan-interval": "1m"
						}
					}
				]
			}
		},
		"masterProfile": {
			"count": 3,
			"dnsPrefix": "spe-k8s",
			"vmSize": "Standard_D4s_v3",
			"osDiskSizeGB": 100,
			"distro": "aks-ubuntu-18.04",
			"vnetSubnetId": "/subscriptions/VNETPATH",
			"firstConsecutiveStaticIP": "10.60.209.112",
			"vnetCidr": "10.60.209.0/25"
		},
		"agentPoolProfiles": [{
				"name": "agentpool",
				"count": 6,
				"vmSize": "Standard_D8s_v3",
				"OSDiskSizeGB": 100,
				"diskSizesGB": [100, 100],
				"availabilityProfile": "VirtualMachineScaleSets",
				"storageProfile": "ManagedDisks",
				"acceleratedNetworkingEnabled": true,
				"vnetSubnetId": "/subscriptions/VNETPATH"
			}
		],
		"linuxProfile": {
			"adminUsername": "azureuser",
			"ssh": {
				"publicKeys": [{
						"keyData": "ssh-rsa KEY"
					}
				]
			}
		},
		"servicePrincipalProfile": {
			"clientId": "CLIENTID",
			"secret": "CLIENT SECRET"
		}
	}
}
```

**Expected behavior**
No public IP and outbound internet rules should be created for private cluster.

**AKS Engine version**
Version: v0.54.0

**Kubernetes version**
1.18

**Additional context**
The private VNET we have policies set by admins do not let us create outbound public internet connection, thus cluster creation will fail when `loadBalancerSku` is set to `Standard`, also we do not want to use basic sku loadbalancer for production use.

`aks-ubuntu-18.04` distro is used which has all the images pre-composed to build the cluster, hence no outbound connection is required.

**Comment by jackfrancis** [comment]
Hi @NaveenkumarIyappan, the public IP and SNAT are to allow *outbound* internet connectivity for workloads running on worker nodes. The functional notion of a private cluster is to restrict public access *to* the control plane.

cc @CecileRobertMichon @devigned to ensure we're in alignment w/ cluster-api capz.

**Comment by CecileRobertMichon** [comment]
Correct, same story in CAPZ. Will add a note to https://capz.sigs.k8s.io/topics/api-server-endpoint.html to that effect.

This is an Azure internal LB characteristic, see https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-troubleshoot#symptom-no-outbound-connectivity-from-standard-internal-load-balancers-ilb

**Comment by rajanbhayana** [comment]
> Hi @NaveenkumarIyappan, the public IP and SNAT are to allow _outbound_ internet connectivity for workloads running on worker nodes. The functional notion of a private cluster is to restrict public access _to_ the control plane.
> 
> cc @CecileRobertMichon @devigned to ensure we're in alignment w/ cluster-api capz.

the AKS cluster rolls out in the spoke, in a typical hub spoke model. Each spoke most likely has a policy for not including any public IP. So having a public IP will cause issues in spoke? Also we want to route all the traffic via the firewall in hub and not straight from spoke. How do we achieve that here now?

**Comment by devigned** [comment]
> having a load balancer with a private IP only for outbound would have helped here?

I'm unclear if that is a question or a statement.

> via the firewall in hub

Are you referring to [Azure Firewall](https://docs.microsoft.com/en-us/azure/firewall/features)? I don't think using an internal load balancer with an Azure Firewall will achieve the same goal as the current solution, the VMs will not have access to the public internet. See: https://docs.microsoft.com/en-us/azure/firewall/integrate-lb#internal-load-balancer. 

Outbound access is kind of painful. We are open to ideas that can make private clusters and outbound access simpler.

**Comment by rajanbhayana** [comment]
> > having a load balancer with a private IP only for outbound would have helped here?
> 
> I'm unclear if that is a question or a statement.

sorry. I should have been clear. I am checking if there is way to rollout a private cluster and not have that load balancer with outbound public IP. 

> 
> > via the firewall in hub
> 
> Are you referring to [Azure Firewall](https://docs.microsoft.com/en-us/azure/firewall/features)? I don't think using an internal load balancer with an Azure Firewall will achieve the same goal as the current solution, the VMs will not have access to the public internet. See: https://docs.microsoft.com/en-us/azure/firewall/integrate-lb#internal-load-balancer.
> 
> Outbound access is kind of painful. We are open to ideas that can make private clusters and outbound access simpler.

any firewall in the hub. this is clear though. I can still route all my outbound via the hub firewall and it will work. 
The key pain point here is the public IP on the load balancer. 

to simplify it, All big enterprise customers will route the outbound via the firewall or will just route all traffic via the hub. not everyone just send traffic to internet via the spoke directly. So it may makes no sense to have a public IP on the load balancer.

<img width="823" alt="1" src="https://user-images.githubusercontent.com/1966429/109645715-545df580-7bab-11eb-9e47-8e586f582cc3.png">

**Comment by devigned** [comment]
Totally get you don't want the public IP, but you do want outbound traffic from the spoke VMs. My concern is that the VMs will not have public internet access without the public IP SNAT on the Load Balancer due to the constraints of outbound traffic in Azure. See the note in image below from [the link I posted above](https://docs.microsoft.com/en-us/azure/firewall/integrate-lb#internal-load-balancer). Using an internal load balancer with the Firewall, the way I read that note is that the spoke VMs will not have access to the internet using a only internal load balancer.

Do you have a configuration which will obviate the need for the outbound load balancer + public IP for SNAT? If so, that would be awesome!

![image](https://user-images.githubusercontent.com/386473/109647649-8af22c80-7b27-11eb-9a26-fe5a629f26c2.png)

**Comment by rajanbhayana** [comment]
you can do it as per the setup below. 
https://github.com/Sumitkup1/AKS_Architecture
Worked with one the guys in my team last year to set it up and totally forgot it existed 

Ideally, When setting up AKS on portal, I dont want to be forced with a standard load balancer with public IP for outbound. There should be an option for just a private load balancer, so that we can roll it out in a spoke and then route all the outbound traffic to the internet via the hub.

**Comment by rajanbhayana** [comment]
We can close this. Its actually documented here in detail - https://docs.microsoft.com/en-us/azure/aks/egress-outboundtype
We need to focus on 2 parameters when rolling out aks. It wont work via portal since portal doesn't allow use to select UDR for outbound but uses standard load balancer with public IP as default. We would need to use cli. 

the 2 parameters to make it fully private - 
--enable-private-cluster (to make aks private) and then expose each service using internal load balancer as per details here - 
https://docs.microsoft.com/en-us/azure/aks/internal-lb

and then for private outbound, use the parameter 
--outbound-type userDefinedRouting
Then you can use the UDRs to send the traffic out via the hub, as desired by most who are using hub/spoke model in azure.

**Comment by jackfrancis** [comment]
Thx @rajanbhayana for providing so much detail on this issue thread, it will help others searching the historical issue queue for similar LB challenges!
