### ISSUE TITLE
Enable "requires VHD" feature flag

### ISSUE THREAD

**Issue by jackfrancis** [Azure/aks-engine#426]
Let's set up a feature flag to test an api model configuration for "VHD compatibility".

**Comment by CecileRobertMichon** [comment]
Thinking more about this, the `BlockOutboundInternet` feature flag already does this... If anything is missing from the VHD deployment will fail because it won't be able to download it. We already have a jenkins pipeline for this - it's currently failing on 0.29.1 because the etcd default is missing from the vhd (etcd 3.2.25 was merged to master before building the VHD but not cherry picked in the release).

**Comment by jadarsie** [comment]
@jackfrancis, Why are you guys keeping this open? Are you and @CecileRobertMichon referring to the same behavior? If not, what behaviors should be triggered by this new "requires VHD"/"VHD compatibility" flag?

I am trying to figure if I can contribute to this issue. But at the same time I am also thinking that if we come up with a simple and cheap validation process for outbound connections, then it should be possible to always run the validation process instead of passing an explicit flag to trigger it.

**Comment by CecileRobertMichon** [comment]
IMO the `BlockOutboundInternet` flag covers this behavior and we can close this issue.
