### ISSUE TITLE
Containers cant ping each other when deploy kubernets V1.18.15 using AKS engine V0.60.1 on Azure stack

### ISSUE THREAD

**Issue by peter201013** [Azure/aks-engine#4391]
When Im trying to deploy a new k8s cluster with V1.18.15 within a custom network on Azure stack like 172.19.0.0/16 we are noticed that the containers cant ping each other although the cluster is deployed successfully and all the nodes and kube-system pods are ready and healthy

- our cluster in consists of 3 master nodes and 2 workers
- Container within the same worker node can communicate with each other successfully but container in different workers can not
- when i tried to deploy another k8s cluster with version 1.16.9 with the same network configuration , it deployed successfully and container are communicate with each other correctly

is there anyone faced an issue like that before ?

**Comment by liykfrank** [comment]
@peter201013 , are you using kubenet or Azure CNI for your container network?
We experienced the same issue with kubenet. And it seems this issue is related with custom network.

**Comment by peter201013** [comment]
@liykfrank  we are using kubenet network with custom network .. But i got the root cause of the issue ..

pod CIDR must be within the virtual network .. this will solve the network issue

**Comment by peter201013** [comment]
Private VNet    152.16.0.0/14
Master Subnet   152.17.0.0/24                              first consecutive ip 152.17.0.5
worker Subnet   152.17.1.0/24 
Pod CIDR        152.16.0.0/16

**Comment by liykfrank** [comment]
@peter201013 , thank you for sharing the details.
From my understanding, in "Kubenet Model" the Pod CIDR should not overlap with Node VNET IP ranges. It may lead to IP conflicts, as azure resource manager doesn't know which IP was assigned to a Pod in Kubernetes cluster.

In my case, I attempt to deploy K8S on Azure stack with AKS-Engine v0.60.1 to a custom VNet.

- VNet Range: 10.0.0.0/16
- Pod CIDR: 10.244.0.0/16
It worked well with AKS-Engine V0.50.2 and AKS 1.16.9.
But the same network topology can not work with AKS-Engine v0.60.1.

It seems this issue is related with a PR:
https://github.com/Azure/aks-engine/pull/3914
After adding the NSG rules to enable the traffic flow between VNet and Pod CIDR, the issue was resolved.

So I think this is a bug in NSG creation. AKS-engine should either allow the traffic flow between VNet and Pod CIDR or attach the NSG to subnet rather than NICs for custom VNet.

**Comment by peter201013** [comment]
@liykfrank  please have a look on the below documentation, which state that cluster subnet must be within virtual network, Also i tried to use the above network schema and it is working fine with latest version 1.18.15  

https://docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-custom-vnet?view=azs-2008#constraints-when-creating-a-custom-virtual-network

**Comment by bridgetkromhout** [comment]
Hi, @liykfrank - it seems Peter has responded with a fix. If you are still using AKS Engine, please be aware that AKS Engine is deprecated and we recommend using AKS instead. Please see https://github.com/Azure/aks-engine#project-status for details; thanks.
