### ISSUE TITLE
Failed to Ensure load balancer - internal load balancers does not support IPv6

### ISSUE THREAD

**Issue by Schreder-Hyperion** [Azure/aks-engine#4428]
**Describe the issue**
When creating an internal load balancer service on a dual-stack-cluster, the service is not created because it throws the error:
`Warning  SyncLoadBalancerFailed  34s (x6 over 3m10s)  service-controller  Error syncing load balancer: failed to ensure load balancer: ensure(nginx/nginx-ipv6-internal): lb(hyp-shared-dev-platform-dualstack-europe-internal) - internal load balancers does not support IPv6
`
**AKS Engine Version***
v0.62.1
**Kubernetes Version**
1.20

**To Reproduce**
1. Create a dual-stack cluster from the examples
2. Create a service on any arbitrary namespace with the annotation `service.beta.kubernetes.io/azure-load-balancer-internal: "true"`
3. Run kubectl describe svc <svc_name>

**Expected behavior**
Internal Inbound load balancer to be created with IPv6 internal address

**Screenshots**
![image](https://user-images.githubusercontent.com/72858686/118998357-4a18ef80-b981-11eb-9310-af2aa8ea41d1.png)

Notify @az-policy-kube

**Comment by Schreder-Hyperion** [comment]
My educated guess is that aks-agent defaults to Basic SKU load balancers instead of using Standard, could you confirm this?

**Comment by bridgetkromhout** [comment]
Hi, @Schreder-Hyperion - Dual-stack is now GA in Kubernetes 1.23, and some details may have changed since you were checking it out in 1.20. Also, AKS Engine is now deprecated, so please use dual-stack with AKS: https://docs.microsoft.com/en-us/azure/aks/configure-kubenet-dual-stack?tabs=azure-cli%2Ckubectl

I will close this issue as no work will be done on AKS Engine around this, but please do provide feedback on AKS if questions arise; thanks!
