### ISSUE TITLE
--client-id and --client-secret must be specified 

### ISSUE THREAD

**Issue by MirzaSikander** [Azure/aks-engine#451]
**Is this a request for help?**:

--- No

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

--- Issue

**What version of aks-engine?**:

--- v.0.29.1

**Kubernetes version**:

**What happened**:
The cluster definition already contains the `client-id` and `client-secret`, yet the command ` aks-engine.exe deploy --subscription-id ### --location eastus --auto-suffix --api-model .\clusterdefinition.json` fails with the error:

```
FATA[0000] failed to load apimodel: --client-id and --client-secret must be specified when --auth-method="client_secret"
```
**What you expected to happen**:
Not be required to specify params if they are already inside the cluster definition file.

**How to reproduce it** (as minimally and precisely as possible):
Specify clientid and client secret inside cluster definition and not specify the parameters `--client-id` and `--client-secret`

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment]
This is by design since https://github.com/Azure/aks-engine/pull/231, @tariq1890 can probably explain in more details.

**Comment by tariq1890** [comment]
@MirzaSikander As Cécile says, this is indeed by design. The credentials that you provide in the CLI is used for authenticating with the Azure API client (much like the `az login`) is actually different from the credentials used for provisioning the Kubernetes cluster. This is one of the fundamental assumptions that have been drilled into aks-engine and has remained as-is. That being said, we are open to redesigning this control flow and possibly to have a single point of authentication.
