### ISSUE TITLE
GPU provisioning doesn't work in air-gapped environment

### ISSUE THREAD

**Issue by mboersma** [Azure/aks-engine#4684]
**Describe the bug**

After #4361 merged, AKS Engine is left without a way to provision GPU nodes without requiring internet downloads.

**Steps To Reproduce**

**Expected behavior**

**AKS Engine version**

**Kubernetes version**

**Additional context**

**Comment by Michael-Sinz** [comment]
@jackfrancis Didn't your changes to aks-engine address the lost dpkgs and thus the egress that resulted?

**Comment by jackfrancis** [comment]
Yes. GPU pool added to "no outbound" test spec on Jan 6:

https://github.com/Azure/aks-engine/pull/4797/files#diff-19336def50eb3c4447f99893620ef2fe95d6042079624e8a192cdec447034e00R17

We have been gating releases on a passing "no outbound" test since June 2021:

https://github.com/Azure/aks-engine/pull/4451/files

Verified by release CI on Jan 13:

https://github.com/Azure/aks-engine/runs/4810970323

We're good to close this issue.
