### ISSUE TITLE
AKS Deployment in Azure Stack Hub - Load Balancing Options for Master Nodes

### ISSUE THREAD

**Issue by zohebs341** [Azure/aks-engine#4951]
Hi Team,

We are planning to deploy AKS in Azure Stack Hub. 

Scenario:

1. If I have one master and multiple worker nodes, then no need to use any load balancing solution.
2. What If I want to go with 3 master nodes and multiple worker nodes, how does it work in the Azure Stack Hub? Do I need to use any load balancing solution for worker nodes to talk to master nodes for load balancing? Or it's not required?

**Comment by bridgetkromhout** [comment]
Hi, @zohebs341! Opening issues in this AKS Engine repo unfortunately will not get you any answers about deploying AKS in Azure Stack Hub. Please open an issue in the Azure Stack Docs repo https://github.com/MicrosoftDocs/azure-stack-docs/issues so that team can guide you in the right direction - thanks!
