### ISSUE TITLE
Asset names for v0.73.0 are wrong (version is missing)

### ISSUE THREAD

**Issue by suzuki-shunsuke** [Azure/aks-engine#5000]
Thank you for your great project.

Asset names for v0.73.0 are wrong.

https://github.com/Azure/aks-engine/releases/tag/v0.73.0

<img width="412" alt="image" src="https://user-images.githubusercontent.com/13323303/200549612-ea52f257-7ac4-4213-bfcf-c2949c41dda5.png">

```
aks-engine--darwin-amd64.tar.gz
aks-engine--darwin-amd64.zip
aks-engine--linux-amd64.tar.gz
aks-engine--linux-amd64.zip
aks-engine--windows-amd64.tar.gz
aks-engine--windows-amd64.zip
```

On the other hand, asset names for v0.72.0 are correct.

https://github.com/Azure/aks-engine/releases/tag/v0.72.0

```
aks-engine-v0.72.0-darwin-amd64.tar.gz
aks-engine-v0.72.0-darwin-amd64.zip
aks-engine-v0.72.0-linux-amd64.tar.gz
aks-engine-v0.72.0-linux-amd64.zip
aks-engine-v0.72.0-windows-amd64.tar.gz
aks-engine-v0.72.0-windows-amd64.zip
```

**Comment by suzuki-shunsuke** [comment]
Oh, the release v0.73.0 was removed.

https://github.com/Azure/aks-engine/releases/tag/v0.73.0

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/13323303/200694229-f5ef6a42-dd01-4025-83ff-5bf5e3023f00.png">

**Comment by bridgetkromhout** [comment]
Hi, @suzuki-shunsuke - we needed to correct an issue. https://github.com/Azure/aks-engine/releases/tag/v0.73.0 is now available.

Because this legacy project is no longer being actively maintained, and will be deprecated soon, have you looked at moving to AKS? It is important that you consider the next option for the workloads you're currently running on AKS Engine. Thanks.

**Comment by suzuki-shunsuke** [comment]
Hi, @bridgetkromhout , thank you for your update.
I see. Thank you for your guide.
