### ISSUE TITLE
Image pull error for k8s-device-plugin in mooncake

### ISSUE THREAD

**Issue by yulin-li** [Azure/aks-engine#5034]
**Describe the bug**

When adding gpu node pool into mooncake, we got image pull error for nvidia `k8s-device-plugin`

``` 
Normal  BackOff  2m43s (x436 over 102m)  kubelet  Back-off pulling image "dockerhub.azk8s.cn/nvidia/oss/nvidia/k8s-device-plugin:1.0.0-beta6"
```

The image path in global cloud is `mcr.microsoft.com/oss/nvidia/k8s-device-plugin:1.0.0-beta6`

**Steps To Reproduce**

**Expected behavior**

**AKS Engine version**

**Kubernetes version**

1.21.4

**Additional context**

**Comment by bridgetkromhout** [comment]
Hi, @yulin-li - this is a GitHub repository for the deprecated self-managed Kubernetes cluster tool AKS Engine. If your question is about AKS, you can use https://github.com/Azure/AKS/issues. No support is available for AKS Engine, so I will close this issue now.

**Comment by Michael-Sinz** [comment]
Note that this is an error in aks-engine - brought on when the image in question was switched from dockerhub to mcr - but the logic to switch dockerhub to the China dockerhub still was there but it switched just mcr -> China dockerhub and not the image path/name and thus it can't pull it correctly.

It should have just kept it as mcr since mcr is available in China (dockerhub has a specific China version/mirror - but we are not to be pulling from dockerhub anyway)

The reason this caused a problem is that the image is already on disk in the disk image (aks-engine disk image) but on disk it is from mcr and thus it does not consider that image valid for dockerhub (be it China or otherwise) and thus tries to pull it and fails.

We (Skyman) can hack a fix for this - specifically since this is an EOL system, but it is a valid bug with respect to how this is handled.

**Comment by jackfrancis** [comment]
To be clear it sounds like we want image pulls from mooncake to reuse the default? E.g.:

- `mcr.microsoft.com/oss/nvidia/k8s-device-plugin:1.0.0-beta6`

And we don't want this? E.g.:

- `mcr.azk8s.cnoss/nvidia/k8s-device-plugin:1.0.0-beta6`

(Or some other mooncake-specific URI that mirrors mcr.microsoft.com)

?

If we simply want nvidia downloads in mooncake to pull from the same URI as we do in public cloud, that's an easy fix.

**Comment by Michael-Sinz** [comment]
Yes, we should pull the same in mooncake as public:  the mcr.microsoft.com/....

I have this hacked in as a fix in our clusters and it addressed the problem.

__
𝕄𝕚𝕔𝕙𝕒𝕖𝕝 𝕊𝕚𝕟𝕫 – Architect – <http://midori/> 緑 – Microsoft
________________________________
