### ISSUE TITLE
Any documentation for recent HNS/wcifs registry changes?

### ISSUE THREAD

**Issue by scottt732** [Azure/aks-engine#5094]
I have been troubleshooting some HNS and SMB-related issues on Windows Server 2019 / Docker 20.10.9 with NAT mode for a while now and #5026 introduces some registry keys that seem to relate to the problems I'm seeing. 

I can't find any docs about these flags but noticed this change & a few of others went into this repo and a handful of others docker/kubernetes-related repos a few weeks after KB5018485.

> Addresses an issue that causes the Host Networking Service (HNS) to stop working. This leads to traffic interruptions. For Windows Server 2019, this change is disabled by default. To turn it on requires a registry key.

By any chance are these related? Are there docs anywhere that explain what they're doing? It will take a bit of trial/error, waiting on CI pipelines to test permutations of these & wait for issues to reappear or not.

```
HKLM:\SYSTEM\CurrentControlSet\Services\hns\State HNSControlFlag -> 0x10, 0x40, or 0x50 (both)
HKLM:\SYSTEM\CurrentControlSet\Services\hns\State EnableCompartmentNamespace -> 1
HKLM:\SYSTEM\CurrentControlSet\Services\wcifs -> 0
```

**Comment by bridgetkromhout** [comment]
Hi, @scottt732! Let's see if @marosset can point you in the right direction.

Meanwhile, I do want to make sure you know that in case you are asking in this repo because you currently use AKS Engine for self-managed K8s, that AKS Engine is reaching end of support; no more updates will happen for this particular tool after K8s 1.24 goes out of support this summer. Hopefully this won't be a problem for your needs, but in case you are in fact using AKS Engine, you should switch to AKS or CAPZ.

**Comment by scottt732** [comment]
Ah thanks. I wasn't aware. Would Azure/AgentBaker make more sense? Happy to open there.

**Comment by marosset** [comment]
I see we have https://github.com/microsoft/Windows-Containers/issues/44 but there isn't more information.
@brasmith-ms @judyliu-ms  do either of you have more info?

**Comment by bridgetkromhout** [comment]
I believe this was discussed; to summarize, if @scottt732 wants to ask any further questions in AgentBaker, that will be a better place. AKS Engine is going out of support this month and this repo will be archived, so this is not a place for ongoing support. Thanks.
