### ISSUE TITLE
Feature Request: update --max-pods without recreating the cluster 

### ISSUE THREAD

**Issue by mathieuherbert** [Azure/aks-engine#542]
**Feature Request:**
The --max-pods flag can only be set at the creation step. To update it we need to destroy and create a new cluster.
We would like to be able to update this value without recreating the cluster.

**Comment by jackfrancis** [comment]
@mathieuherbert you could try changing manually the value in the `apimodel.json` referenced in an `aks-engine upgrade` command. (Are you successfully using `aks-engine upgrade` in your cluster mgmt toolchain?)

**Comment by mathieuherbert** [comment]
Hi, @jackfrancis I am using AKS through Azure API and managed with Terraform. In the AKS documentation there is a comment about this limitation:
```
When you deploy an AKS cluster with the Azure CLI or a Resource Manager template, this value is configurable up to 110 pods per node. You can't configure max pods per node after you've already deployed an AKS cluster, or if you deploy a cluster using the Azure portal.
```
https://docs.microsoft.com/azure/aks/container-service-quotas

**Comment by palmerabollo** [comment]
I opened a related isssue https://github.com/Azure/aks-engine/issues/528 some days ago. It is really hard (sometimes impossible) to upgrade an existing cluster.

I think aks-engine should be able to detect what changes should be applied to honor the new apimodel.json in an existing cluster, create a plan to apply the changes it needs, and rolling update the cluster without service disruption. We are able to do this with kops in AWS/GCE but kops does not support Azure yet (there is a lot of interest in the community btw https://github.com/kubernetes/kops/issues/3957) and aks-engine is very limited in this regard.

**Comment by AlexBevan** [comment]
Just here to add a +1 one this!

**Comment by marc-mueller** [comment]
Just here to add a +1, too!

**Comment by sai-li** [comment]
Just here to add a +1.

**Comment by chauhanprateek89** [comment]
Here to add +1 to this

**Comment by marouanel** [comment]
Another + 1 to this

**Comment by VincentSurelle** [comment]
Another one gives the +1 🎵

**Comment by darthchudi** [comment]
Here to add +1 to this

**Comment by Blarne** [comment]
Another + 1 to this

**Comment by hameno** [comment]
Still very much needed

**Comment by ammarsajid** [comment]
another +1

**Comment by iMacX** [comment]
+1

**Comment by jackfrancis** [comment]
Thanks, everyone on this thread for your patience.

In fact updating `--max-pods` is possible by using `aks-engine upgrade` or `aks-engine scale` (the latter only works against node pool vms, but this particular configuration change is usually desired on schedulable nodes, not control plane nodes) with a modified api model JSON input to the `upgrade` or `scale` command. I'll demonstrate an example of using `upgrade` below:

First, I create a new, small cluster w/ aks-engine. It looks like this:

```
$ kubectl get nodes -o json
2020/01/30 13:43:02 NAME                                 STATUS   ROLES    AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
k8s-agentpool1-21172650-vmss000000   Ready    agent    18s   v1.15.7   10.240.0.34    <none>        Ubuntu 16.04.6 LTS   4.15.0-1066-azure   docker://3.0.8
k8s-agentpool1-21172650-vmss000001   Ready    agent    18s   v1.15.7   10.240.0.65    <none>        Ubuntu 16.04.6 LTS   4.15.0-1066-azure   docker://3.0.8
k8s-master-21172650-0                Ready    master   18s   v1.15.7   10.255.255.5   <none>        Ubuntu 16.04.6 LTS   4.15.0-1066-azure   docker://3.0.8
```

The resultant `apimodel.json` shows us the `--max-pods` configuration:

```
$ grep -e "--max-pods" _output/kubernetes-westus2-85390/apimodel.json
          "--max-pods": "30",
          "--max-pods": "30",
            "--max-pods": "30",
```

And doing a simple pod scale out shows the nodes adhering to the above configuration:

```
$ kubectl get pods --all-namespaces -o wide | grep 'k8s-agentpool1-21172650-vmss000000' | wc -l
      30
$ k get pods --all-namespaces -o wide | grep 'Pending' | wc -l
      87
```

The above demonstrates that we have more pods than our node count + `--max-pods` configuration will allow us to schedule on the cluster.

Next, I edit that `apimodel.json` file to update the `--max-pods` value (it's in the `kubeletConfig` config object, in the main `orchestratorProfile.kubernetesConfig` config object; and in the `masterProfile.kubernetesConfig` config object to configure the control plane vms; and in the `kubernetesConfig` config object for each `agentPoolProfiles` array item (my cluster above has just one node pool). After updating the `--max-pods` value everywhere, the `apimodel.json` file looks like this:

```
$ grep -e "--max-pods" _output/kubernetes-westus2-85390/apimodel.json
          "--max-pods": "100",
          "--max-pods": "100",
            "--max-pods": "100",
```

So, after modifying that file, I can pass it as input to `aks-engine upgrade`, which will go one-node-at-a-time through the cluster, and pave a new vm with the updated configuration. E.g.:

```
$ bin/aks-engine upgrade --force --subscription-id $TEST_AZURE_SUB_ID --api-model _output/kubernetes-westus2-85390/apimodel.json --location westus2 --resource-group kubernetes-westus2-85390 --upgrade-version 1.15.7 --client-id $TEST_AZURE_SP_ID --client-secret $TEST_AZURE_SP_PW
```

(Note I used the `--force` option, and passed in the existing version (1.15.7) of Kubernetes already running on the cluster to the `--upgrade-version` argument, essentially declaring that I'm not changing the version of k8s, but am using `upgrade` to deliver a new node configuration across the cluster.)

Upgrade takes a while, but after it's done, we can do the equivalent pod scale out test and see that we have more pod-per-node scheduling overhead. Here's the cluster post-upgrade:

```
$ kubectl get nodes
NAME                                 STATUS   ROLES    AGE   VERSION
k8s-agentpool1-21172650-vmss000002   Ready    agent    31m   v1.15.7
k8s-agentpool1-21172650-vmss000003   Ready    agent    26m   v1.15.7
k8s-master-21172650-0                Ready    master   53m   v1.15.7
```

(Note that the nodes have different names, which is a result of the VMSS adding nodes w/ new names.)

Let's look at what these new nodes can do:

```
$ k get pods --all-namespaces -o wide | grep 'k8s-agentpool1-21172650-vmss000002' | wc -l
     100
$ k get pods --all-namespaces -o wide | grep 'k8s-agentpool1-21172650-vmss000003' | wc -l
     100
$ k get pods --all-namespaces -o wide | grep 'Pending' | wc -l
      62
```

(The last line showing `Pending` pods demonstrates that we're indeed at the limits of what our nodes can schedule, but now that limit is `100` instead of `30`.)

Can folks read through the above narrative and comment if this is a workable solution? If so, we'll add some detailed documentation around this to better guide folks through the current working patterns for doing these cluster configuration changes.

**Comment by rbitia** [comment]
@jackfrancis mentioned a manual workaround above, so closing this issue!

**Comment by GustavoAmerico** [comment]
after analyzing the output of the command .... I concluded that the maximum pod configuration for us was in the node pool. So I decided to create a pool in the existing cluster, see the steps.

workaround:
1. I created an new node pool
`az aks nodepool add --cluster-name <you aks cluster name> -g <your-aks-resource-group> --max-pods=110 --name newpool --enable-cluster-autoscaler --min-count 1 --max-count 1 -c 1 -s <machine size>`

1. Scale down the node of agentpool one per one and scale up newpool as necessary

1. I tried to remove the default pool, but the cli show an error
The message is: **Operation failed with status: 'Bad Request'. Details: There has to be at least one system agent pool.**


Expectative:
1. run `az aks nodepool update --cluster-name <you aks cluster name> --name <pool name>  maxpods=XXX` (currently it doesn't work)
1. cleaning the default pool if other pool was work


Conclusion: 
now i have two pools with the same computational resources, but one is scaled with a single machine and the other has automatic scale

**Comment by jackfrancis** [comment]
Thanks for sharing @GustavoAmerico! FYI this thread is about managing clusters created with AKS Engine (which is a distinct tool from the Azure AKS managed service).

**Comment by robinwillems** [comment]
> after analyzing the output of the command .... I concluded that the maximum pod configuration for us was in the node pool. So I decided to create a pool in the existing cluster, see the steps.
> 
> workaround:
> 
> 1. I created an new node pool
>    `az aks nodepool add --cluster-name <you aks cluster name> -g <your-aks-resource-group> --max-pods=110 --name newpool --enable-cluster-autoscaler --min-count 1 --max-count 1 -c 1 -s <machine size>`
> 2. Scale down the node of agentpool one per one and scale up newpool as necessary
> 3. I tried to remove the default pool, but the cli show an error
>    The message is: **Operation failed with status: 'Bad Request'. Details: There has to be at least one system agent pool.**
> 
> Expectative:
> 
> 1. run `az aks nodepool update --cluster-name <you aks cluster name> --name <pool name>  maxpods=XXX` (currently it doesn't work)
> 2. cleaning the default pool if other pool was work
> 
> Conclusion:
> now i have two pools with the same computational resources, but one is scaled with a single machine and the other has automatic scale

Hi, @GustavoAmerico You can change the new nodepool to become a system nodepool by running
az aks nodepool update -g myResourceGroup --cluster-name myAKSCluster -n MyNewNodePool --mode system

After that you can delete the 1ste (original nodepool) by running:
az aks nodepool delete -g myResourceGroup --cluster-name myAKSCluster -n MyOriginalNodePool

Hope it helps!

**Comment by HalidCisse** [comment]
Please we need this!

**Comment by jackfrancis** [comment]
Hi @HalidCisse, do you need this for AKS clusters, or are you managing your own clusters created with the aks-engine tool?

**Comment by HalidCisse** [comment]
@jackfrancis yes. Currently, I recreate the node with new maxPods as a workaround.

**Comment by jackfrancis** [comment]
@palma21 Is there a relevant feature request issue for AKS to enable re-configuring an existing cluster with a different maxPods setting?
