### ISSUE TITLE
Kube-addon-manager tries to create Policy

### ISSUE THREAD

**Issue by sylr** [Azure/aks-engine#635]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** : issue

---

**What version of aks-engine?**: v0.31.1

---

```
error: unable to recognize "/etc/kubernetes/addons/audit-policy.yaml": no matches for kind "Policy" in version "audit.k8s.io/v1beta1"
```

As far I understand this spec should not be created by the addon-manager but be passed as argument to the api-server: https://stackoverflow.com/questions/54238430/cant-create-policy-no-matches-for-kind-policy

**Kubernetes version**: 1.13.4

**Comment by sylr** [comment]
https://github.com/sylr/aks-engine/commit/81af99ad47a04fcf4e1ae705f97b722b8479d299

**Comment by allantargino** [comment]
Hi @sylr, just a comment about the fix https://github.com/sylr/aks-engine/commit/81af99ad47a04fcf4e1ae705f97b722b8479d299: we shouldn't use the `/etc/kubernetes/manifests/` folder for this.
Since we are using a kubelet to run master components (inside `/etc/kubernetes/manifests/` ), it would generate a side effect as described in https://github.com/Azure/aks-engine/issues/633#issuecomment-490087182
Maybe, a better fix would use a separated folder (than `addons` or `manifests`).
